### ISSUE TITLE
find_RCRJ_and_classify.py

### ISSUE THREAD

**Issue by luhan125** [PSSUN/CircCode#10]
Hello,

When I run "python3.7 find_RCRJ_and_classify.py -y config.yaml". I got the err :
Traceback (most recent call last):
  File "find_RCRJ_and_classify.py", line 8, in <module>
    import rpy2.robjects as robjects
  File "/software/biosoft/software/python/python2019/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 27, in <module>
    from . import language
  File "/software/biosoft/software/python/python2019/lib/python3.7/site-packages/rpy2/robjects/language.py", line 16, in <module>
    _str2lang = ri.baseenv['str2lang']
  File "/software/biosoft/software/python/python2019/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 44, in _
    cdata = function(*args, **kwargs)
  File "/software/biosoft/software/python/python2019/lib/python3.7/site-packages/rpy2/rinterface_lib/_rinterface_capi.py", line 282, in _
    robj = function(*args, **kwargs)
  File "/software/biosoft/software/python/python2019/lib/python3.7/site-packages/rpy2/rinterface_lib/sexp.py", line 355, in __getitem__
    raise KeyError("'%s' not found" % key)
KeyError: "'str2lang' not found"

I guess the err is related to previous steps, because there are no "junction_result" and "junction_filter_result files" in tmp_file folder. And all files I used are from your example, could you give me some advice?

Thank you very much!

Lu

**Comment by PSSUN** [comment]
Hi,
This bucause you used the old version of CircCode.
please re-download the new version of circcode 
`git clone https://github.com/PSSUN/CircCode.git`
and remove all the tmp file, then run those three script:

make_virtual_genomes.py
map_to_virtual_genomes.py 
find_RCRJ_and_classify.py

In new version of CircCode, you only need three script to run all process and the bug you said has been fixed.

**Comment by PSSUN** [comment]
My wechat number is 
`LIFEOrzME`
if you have more question, you're welcome to contact me on WeChat.
