### ISSUE TITLE
find_RCRJ_and_classify.py

### ISSUE THREAD

**Issue by Tanv1** [PSSUN/CircCode#14]
Hey

I'm using CircCode, but every time I am facing the same problem. I would appreciate any help to resolve this issue:

When I run - find_RCRJ_and_classify.py it gives following error:
**Error in (function (edges, n = max(edges), directed = TRUE)  :
  At type_indexededgelist.c:117 : cannot create empty graph with negative number of vertices, Invalid value
Calls: classification -> createNet -> graph -> do.call -> <Anonymous>
In addition: Warning message:
In max(edges) : no non-missing arguments to max; returning -Inf
Execution halted
Classify successfully!
sed: can't read /userdata/lab/RPFAligned.sortedByCoord.out.bam.merge_result.RCRJ_result.csv_translated_circ.fa: No such file or directory
Traceback (most recent call last):
  File "find_RCRJ_and_classify.py", line 369, in <module>
    main()
  File "find_RCRJ_and_classify.py", line 355, in main
    classify(coding_seq,
  File "find_RCRJ_and_classify.py", line 102, in classify
    seqs = SeqIO.parse(final_trans_file, 'fasta')
  File "/home/lab/.conda/envs/circcode_env/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line 607, in parse
    return iterator_generator(handle)
  File "/home/lab/.conda/envs/circcode_env/lib/python3.8/site-packages/Bio/SeqIO/FastaIO.py", line 183, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/home/lab/.conda/envs/circcode_env/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", line 47, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: '/userdata/lab/RPFAligned.sortedByCoord.out.bam.merge_result.RCRJ_result.csv_translated_circ.fa'**

Please note that -

"**RPFAligned.sortedByCoord.out.bam.merge_result.RCRJ_result.csv_translated_circ.fa**" no such file is getting generated after mapping in previous step.

Could you help me figure out this? Thanks in advance.

Best,

Tanvi

**Comment by lbwfff** [comment]
I encountered the same error
```
Execution halted
sed: can't read /home/leelee/tools/circcode/CircCode-master/test/LC501_tumor_RPFAligned.sortedByCoord.out.bam.merge_result.RCRJ_result.csv_translated_circ.fa: No such file or directory
find_RCRJ_and_classify.py:327: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  fileload = yaml.load(file)
/home/leelee/tools/circcode/CircCode-master/test/test.fa
Classify successfully!
Traceback (most recent call last):
  File "find_RCRJ_and_classify.py", line 369, in <module>
    main()
  File "find_RCRJ_and_classify.py", line 363, in main
    use_classify)
  File "find_RCRJ_and_classify.py", line 102, in classify
    seqs = SeqIO.parse(final_trans_file, 'fasta')
  File "/home/leelee/miniconda3/envs/circcode/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 605, in parse
    return iterator_generator(handle)
  File "/home/leelee/miniconda3/envs/circcode/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py", line 183, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/home/leelee/miniconda3/envs/circcode/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 48, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/leelee/tools/circcode/CircCode-master/test/LC501_tumor_RPFAligned.sortedByCoord.out.bam.merge_result.RCRJ_result.csv_translated_circ.fa'
```
Does anyone know how to solve such an error?
