### ISSUE TITLE
find_RCRJ_and_classify.py error

### ISSUE THREAD

**Issue by gnilihzeux** [PSSUN/CircCode#8]
We met an error while perform 'find_RCRJ_and_classify.py', which is as follow: 
```
~/miniconda3/lib/python3.6/site-packages/Bio/Seq.py:2715: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning)
Traceback (most recent call last):
  File "find_RCRJ_and_classify.py", line 292, in <module>
    main()
  File "find_RCRJ_and_classify.py", line 288, in main
    find_longest(tmp_file_location, ribo_name, result_file_location, number)
  File "find_RCRJ_and_classify.py", line 115, in find_longest
    end = seq.id.split(':')[-1].split('-')[1]
IndexError: list index out of range
```
 My python is poor, could you please fix it ?

**Comment by PSSUN** [comment]
We have fixed this error, please clone the The latest version of CircCode.
